In [2]:
import torch


x1 = torch.arange(12).reshape(3,4)
x2 = torch.arange(12).reshape((3,4))
print(x1)
print(x2)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [4]:
# 广播，x1复制列，x2复制行
x1 = torch.arange(3).reshape(3,1)
x2 = torch.arange(2).reshape(1,2)
print(x1)
print(x2)
print(x1+x2)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [ ]:
# 广播，x1复制列，x2复制行
x1 = torch.arange(6).reshape(3,2)
x2 = torch.arange(4).reshape(1,4)
print(x1)
print(x2)
# print(x1+x2) # error 广播机制也不是任何情况都能广播

tensor([[0, 1],
        [2, 3],
        [4, 5]])
tensor([[0, 1, 2, 3]])


RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 1

In [12]:
# 广播，x1复制列，x2复制行
x1 = torch.arange(6).reshape(1,2,3)
x2 = torch.arange(3).reshape(1,1,3)
print(x1)
print(x2)
print(x1+x2)

tensor([[[0, 1, 2],
         [3, 4, 5]]])
tensor([[[0, 1, 2]]])
tensor([[[0, 2, 4],
         [3, 5, 7]]])


In [25]:
x1 = torch.arange(6).reshape(2,3)
print(x1)
print(x1.sum(axis=0)) # [1,3]
print(x1.sum(axis=1)) # [1,2]


tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([3, 5, 7])
tensor([ 3, 12])


In [33]:
x1 = torch.arange(24).reshape(2,3,4)
print(x1)
print(len(x1))
print("-----------------------------")
print(x1.sum(axis=0)) # [3,4]
print(x1.sum(axis=1)) # [2.4]
print(x1.sum(axis=2)) # [2,3]

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
2
-----------------------------
tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])
tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])
tensor([[ 6, 22, 38],
        [54, 70, 86]])


In [18]:

x1 = torch.arange(20).reshape(5,4)
x2 = torch.arange(4)
print(x1)
print(x2)

print(torch.mv(x1,x2))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([0, 1, 2, 3])
tensor([ 14,  38,  62,  86, 110])


In [22]:

x1 = torch.arange(20).reshape(5,4)
x2 = torch.arange(12).reshape(4,3)

print(x1)
print(x2)

print(torch.mm(x1,x2))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
tensor([[ 42,  48,  54],
        [114, 136, 158],
        [186, 224, 262],
        [258, 312, 366],
        [330, 400, 470]])


In [24]:

x1 = torch.arange(4).reshape(2,2)
x2 = torch.arange(4).reshape(2,2)

print(x1)
print(x2)

print(torch.mul(x1,x2))
print(x1*x2)



tensor([[0, 1],
        [2, 3]])
tensor([[0, 1],
        [2, 3]])
tensor([[0, 1],
        [4, 9]])
tensor([[0, 1],
        [4, 9]])


In [36]:
x = torch.arange(6, dtype=torch.float32).reshape(2,3)


print(x)
print(torch.linalg.norm(x))
print(torch.sqrt(torch.mul(x,x).sum()))

tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor(7.4162)
tensor(7.4162)
